### PR TITLE
Clean up duplicated keywords

### PR DESCRIPTION
**Pull request by fcsonline**
Removed some keywords that were duplicated in the dialect configuration.

This is the list of duplicated keywords that have been detected:

```
Duplicated keyword 'path'. Overwriting with a Type
Duplicated keyword 'without'. Overwriting with a Type
Duplicated keyword 'zone'. Overwriting with a Type
Duplicated keyword 'with'. Overwriting with a Type
Duplicated keyword 'blob'. Overwriting with a Type
Duplicated keyword 'year'. Overwriting with a Type
Duplicated keyword 'connect'. Overwriting with a Builtin
Duplicated keyword 'exit'. Overwriting with a Builtin
Duplicated keyword 'go'. Overwriting with a Builtin
Duplicated keyword 'blob'. Overwriting with a Type
Duplicated keyword 'year'. Overwriting with a Type
Duplicated keyword 'connect'. Overwriting with a Builtin
Duplicated keyword 'exit'. Overwriting with a Builtin
Duplicated keyword 'go'. Overwriting with a Builtin
Duplicated keyword 'cursor'. Overwriting with a Type
Duplicated keyword 'table'. Overwriting with a Type
Duplicated keyword 'blob'. Overwriting with a Type
Duplicated keyword 'year'. Overwriting with a Type
Duplicated keyword 'binary'. Overwriting with a Builtin
Duplicated keyword 'check'. Overwriting with a Builtin
Duplicated keyword 'exit'. Overwriting with a Builtin
Duplicated keyword 'limit'. Overwriting with a Builtin
Duplicated keyword 'open'. Overwriting with a Builtin
Duplicated keyword 'output'. Overwriting with a Builtin
Duplicated keyword 'read'. Overwriting with a Builtin
Duplicated keyword 'schema'. Overwriting with a Builtin
Duplicated keyword 'session'. Overwriting with a Builtin
Duplicated keyword 'array'. Overwriting with a Type
Duplicated keyword 'boolean'. Overwriting with a Type
Duplicated keyword 'char'. Overwriting with a Type
Duplicated keyword 'date'. Overwriting with a Type
Duplicated keyword 'decimal'. Overwriting with a Type
Duplicated keyword 'object'. Overwriting with a Type
Duplicated keyword 'blob'. Overwriting with a Type
Duplicated keyword 'dec'. Overwriting with a Type
Duplicated keyword 'describe'. Overwriting with a Builtin
Duplicated keyword 'escape'. Overwriting with a Builtin
Duplicated keyword 'exec'. Overwriting with a Builtin
Duplicated keyword 'execute'. Overwriting with a Builtin
Duplicated keyword 'long'. Overwriting with a Builtin
Duplicated keyword 'release'. Overwriting with a Builtin
Duplicated keyword 'size'. Overwriting with a Builtin
Duplicated keyword 'time'. Overwriting with a Builtin
```

The main reason for this change is to guarantee the styling and highlighting 
of the most important tokens in the language.

image

In this case, `LIMIT` is a standard SQL token, but also a builtin keyword for SQLite

### CODE REVIEW

**Comment by marijnh** [comment]
Wouldn't a more reasonable fix be to remove the word from the list of builtins for SQLite?

**Comment by fcsonline** [comment]
@marijnh It can be a solution. I added a check to know if something common and it detected many.

**Comment by fcsonline** [comment]
Ok. I'll do this then.

**Comment by fcsonline** [comment]
Done. Let me know what do you think.

**Comment by marijnh** [comment]
Thanks! Merged as 1b848bb , which is your patch without the dynamic check/warning.

**Comment by fcsonline** [comment]
I added the warning to catch future duplicates, but it is ok.

**Pull request closed without merging**
